	[[maps.layers]]
	name = "main_roads" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM main_roads_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "farms" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM farms_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "aerodromes_polygon" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM aerodromes_polygon_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "forest" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM forest_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "grassland" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM grassland_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "lakes" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM lakes_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "medical_polygon" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM medical_polygon_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "military" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM military_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "residential" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM residential_3857 WHERE wkb_geometry && !BBOX!"

	[[maps.layers]]
	name = "schools_polygon" 			# will be encoded as the layer name in the tile
	provider = "tanzania_osm"	# must match a data provider
	minzoom = 5 
	maxzoom = 20
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM schools_polygon_3857 WHERE wkb_geometry && !BBOX!"
